[build-system]
requires = ["maturin>=1.4,<2.0"]
build-backend = "maturin"

[project]
name = "libgrapplefrc-py"
requires-python = ">=3.10"
classifiers = [ ]
dynamic = ["version"]

[tool.maturin]
features = ["pyo3/extension-module"]
