def can_bridge_tcp() -> None: ...

class LaserCAN:
    def __init__(self): ...
    def start_ranging(self) -> None: ...
    def get_measurement(self) -> LaserCanMeasurement: ...

class LaserCanMeasurement:
    def __init__(self): ...
    def distance_mm(self) -> int: ...

class LaserCanRoi:
    def __init__(self): ...

class LaserCanTimingBudget:
    Short: "LaserCanTimingBudget"
    Medium: "LaserCanTimingBudget"
    Long: "LaserCanTimingBudget"

class LaserCanRangingMode:
    Short: "LaserCanRangingMode"
    Medium: "LaserCanRangingMode"
    Long: "LaserCanRangingMode"

class MitoCANdria:
    def __init__(self): ...
    def send(self, msg: bytes) -> None: ...
    def read(self) -> bytes: ...
