[package]
name = "grapplefrcdriver"
version = "2024.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "grapplefrcdriver"
crate-type = ["lib", "cdylib", "staticlib"]

[dependencies]
anyhow = "1.0.75"
bounded-static = "0.7.0"
grapple-frc-msgs = "~2024.3.0"
jni = "0.21.1"

[build-dependencies]
cbindgen = "0.26.0"
bindgen = "0.53.1"
